grpc:
  host: "0.0.0.0"
  port: 5002
  connect_timeout: 3
  max_pool_size: 200

http:
  host: "0.0.0.0"
  port: 8081

log:
  level: debug
  file_path: ./logs/ceramicraft-order-mservice.log

mysql:
  host: "127.0.0.1" # 127.0.0.1 mysql-container
  port: "3306"
  userName: "root"
  dbName: "order_db"

commodityClient:
  host: "127.0.0.1" # ceramicraft-commodity-mservice 127.0.0.1
  port: 5001

paymentClient:
  host: "127.0.0.1"
  port: 5003

kafka:
  host: "localhost"
  port: 9092

redis:
  host: "127.0.0.1"
  port: 6379
