basePath: /order-ms/v1
definitions:
  api.Response:
    properties:
      data: {}
      error:
        type: string
      msg:
        type: string
      status:
        type: integer
    type: object
  types.OrderInfo:
    properties:
      order_item_list:
        description: 订单商品列表
        items:
          $ref: '#/definitions/types.OrderItemInfo'
        type: array
      receiver_address:
        description: 收货地址
        type: string
      receiver_country:
        description: 收货人国家
        type: string
      receiver_first_name:
        description: 收货人姓名
        type: string
      receiver_last_name:
        description: 收货人姓名
        type: string
      receiver_phone:
        description: 收货人电话
        type: string
      receiver_zip_code:
        description: 收货人邮政编码
        type: integer
      remark:
        description: 备注
        type: string
    type: object
  types.OrderItemInfo:
    properties:
      price:
        type: integer
      product_id:
        type: integer
      product_name:
        type: string
      quantity:
        type: integer
    type: object
info:
  contact: {}
  description: 订单微服务相关接口
  title: 订单服务 API
  version: "1.0"
paths:
  /customer/create:
    post:
      consumes:
      - application/json
      description: 创建一个新订单
      parameters:
      - description: 订单信息
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/types.OrderInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: 创建订单
      tags:
      - Order
swagger: "2.0"
